### ISSUE TITLE
Add a link linked back for https://dimension.im 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Website#7]
So ppl can find more info

**Comment by Tedko** [comment]
add it for the `/about` ? (simply link it to dimension.im )

**Comment by neruthes** [comment]
Use apex instead of www subdomain

**Comment by septs** [comment]
Add footer area:

```html
<p>Tressercube is a owned of <a href="https://www.dimension.im">Dimension</a>.</p>
```

**Comment by neruthes** [comment]
I prefer

```
<p>Tessercube is developed by <a href="https://dimension.im/">Dimension</a>.</p>
```

or


```
<p>Tessercube is maintained by <a href="https://dimension.im/">Dimension</a>.</p>
```

**Comment by septs** [comment]
@neruthes same time apply to https://maskbook.com?

**Comment by neruthes** [comment]
> @neruthes same time apply to https://maskbook.com?

Agreed.

**Comment by yisiliu** [comment]
I'd suggest 
`<p>Tessercube is developed and maintained by <a href="https://dimension.im/">Dimension</a>.</p>`

**Comment by neruthes** [comment]
> I'd suggest
> `<p>Tessercube is developed and maintained by <a href="https://dimension.im/">Dimension</a>.</p>`

Nice.

**Comment by septs** [comment]
> I'd suggest
> `<p>Tessercube is developed and maintained by <a href="https://dimension.im/">Dimension</a>.</p>`

Suji Reply:
>"Tessercube is developed by Dimension"
